<?php

declare(strict_types=1);

return [
    [
        'id' => 'module_readme',
        'name' => 'Module README',
        'description' => 'Standard README describing config, CLI, telemetry, and integration hooks.',
        'file' => __DIR__ . '/module-readme.md',
        'tags' => ['docs', 'bootstrap'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-write', 'blackcat-darkmesh-ao'],
        'placeholders' => [
            ['token' => 'MODULE_NAME', 'description' => 'Display name for the repository.', 'required' => true],
            ['token' => 'DESCRIPTION', 'description' => 'One-line description/mission.', 'required' => true],
            ['token' => 'CLI_USAGE', 'description' => 'CLI example to surface in README.', 'default' => 'php bin/<repo>'],
            ['token' => 'TELEMETRY_DESC', 'description' => 'How telemetry is exposed (Prometheus endpoints, etc).', 'default' => 'Exports Prometheus metrics.'],
        ],
    ],
    [
        'id' => 'module_roadmap',
        'name' => 'Module Roadmap',
        'description' => 'Stage-by-stage roadmap stub referencing integration partners.',
        'file' => __DIR__ . '/module-roadmap.md',
        'tags' => ['docs', 'roadmap'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-write', 'blackcat-darkmesh-ao'],
        'placeholders' => [
            ['token' => 'MODULE_NAME', 'description' => 'Repository display name.', 'required' => true],
            ['token' => 'VISION', 'description' => 'North-star goal for the module.', 'required' => true],
            ['token' => 'STAGE1_FOCUS', 'description' => 'Stage 1 focus description.', 'required' => true],
            ['token' => 'STAGE2_FOCUS', 'description' => 'Stage 2 focus description.', 'required' => true],
            ['token' => 'COMPLIANCE_OWNER', 'description' => 'Person/alias accountable for compliance sign-off.', 'default' => 'governance@blackcat'],
        ],
    ],
    [
        'id' => 'gateway_search_shell_core',
        'name' => 'Gateway Search Shell - Core',
        'description' => 'Composable shell for gateway search pages; inject rendered menu/search/results/footer fragments.',
        'file' => __DIR__ . '/gateway-search-shell-core.html',
        'tags' => ['gateway', 'search', 'ux', 'shell', 'component-kit', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Document title used by browser tabs.', 'required' => true],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array used when index API is unavailable.', 'default' => '[]'],
            ['token' => 'MENU_COMPONENT', 'description' => 'Rendered menu fragment HTML.', 'required' => true],
            ['token' => 'SEARCH_COMPONENT', 'description' => 'Rendered search/hero fragment HTML.', 'required' => true],
            ['token' => 'RESULTS_COMPONENT', 'description' => 'Rendered index/results fragment HTML.', 'required' => true],
            ['token' => 'FOOTER_COMPONENT', 'description' => 'Rendered footer fragment HTML.', 'required' => true],
            ['token' => 'SHELL_BODY_CLASS', 'description' => 'Optional extra class string for shell wrapper.', 'default' => ''],
            ['token' => 'SHELL_EXTRA_CSS', 'description' => 'Optional extra CSS appended after shell defaults.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_menu_pulse',
        'name' => 'Gateway Component Menu - Pulse',
        'description' => 'Neon/glass menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-pulse.html',
        'tags' => ['gateway', 'component', 'menu', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#catalog\">Catalog</a><a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#explore\">Explore</a><a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_menu_forge',
        'name' => 'Gateway Component Menu - Forge',
        'description' => 'Brutalist menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-forge.html',
        'tags' => ['gateway', 'component', 'menu', 'forge', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#catalog\">Catalog</a><a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#explore\">Explore</a><a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_menu_zenith',
        'name' => 'Gateway Component Menu - Zenith',
        'description' => 'Editorial menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-zenith.html',
        'tags' => ['gateway', 'component', 'menu', 'zenith', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"hover:text-slate-900/70\" href=\"#catalog\">Catalog</a><a class=\"hover:text-slate-900/70\" href=\"#explore\">Explore</a><a class=\"hover:text-slate-900/70\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_search_pulse',
        'name' => 'Gateway Component Search - Pulse',
        'description' => 'Neon hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-pulse.html',
        'tags' => ['gateway', 'component', 'search', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Discover verified pages across the mesh.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Find route, domain, or page id...'],
        ],
    ],
    [
        'id' => 'gateway_component_search_atlas',
        'name' => 'Gateway Component Search - Atlas',
        'description' => 'Brutalist hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-atlas.html',
        'tags' => ['gateway', 'component', 'search', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Route through the public mesh with deterministic records.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'domain:example.com or route:/about'],
        ],
    ],
    [
        'id' => 'gateway_component_search_lumen',
        'name' => 'Gateway Component Search - Lumen',
        'description' => 'Editorial hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-lumen.html',
        'tags' => ['gateway', 'component', 'search', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Search by route, domain, or page id.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Try route:/about or page:contact'],
        ],
    ],
    [
        'id' => 'gateway_component_results_pulse',
        'name' => 'Gateway Component Results - Pulse',
        'description' => 'Neon result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-pulse.html',
        'tags' => ['gateway', 'component', 'results', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_results_atlas',
        'name' => 'Gateway Component Results - Atlas',
        'description' => 'Brutalist result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-atlas.html',
        'tags' => ['gateway', 'component', 'results', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_results_lumen',
        'name' => 'Gateway Component Results - Lumen',
        'description' => 'Editorial result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-lumen.html',
        'tags' => ['gateway', 'component', 'results', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_pulse',
        'name' => 'Gateway Component Footer - Pulse',
        'description' => 'Neon footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-pulse.html',
        'tags' => ['gateway', 'component', 'footer', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"hover:text-cyan-200\" href=\"#\">Status</a><a class=\"hover:text-cyan-200\" href=\"#\">Policy</a><a class=\"hover:text-cyan-200\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_atlas',
        'name' => 'Gateway Component Footer - Atlas',
        'description' => 'Brutalist footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-atlas.html',
        'tags' => ['gateway', 'component', 'footer', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"underline\" href=\"#\">Status</a><a class=\"underline\" href=\"#\">Policy</a><a class=\"underline\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_lumen',
        'name' => 'Gateway Component Footer - Lumen',
        'description' => 'Editorial footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-lumen.html',
        'tags' => ['gateway', 'component', 'footer', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"hover:text-slate-900\" href=\"#\">Status</a><a class=\"hover:text-slate-900\" href=\"#\">Policy</a><a class=\"hover:text-slate-900\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_login_cipher',
        'name' => 'Gateway Component Auth Login - Cipher',
        'description' => 'Structured auth login fragment with validation and reveal toggle.',
        'file' => __DIR__ . '/components/auth-login-variant-cipher.html',
        'tags' => ['gateway', 'component', 'auth', 'login', 'cipher', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FORGOT_HREF', 'description' => 'Token for forgot href.', 'default' => '#'],
            ['token' => 'LOGIN_ACTION', 'description' => 'Token for login action.', 'default' => '#'],
            ['token' => 'LOGIN_CTA_LABEL', 'description' => 'Token for login cta label.', 'default' => 'login cta label'],
            ['token' => 'LOGIN_METHOD', 'description' => 'Token for login method.', 'default' => 'POST'],
            ['token' => 'LOGIN_SUBTITLE', 'description' => 'Token for login subtitle.', 'default' => ''],
            ['token' => 'LOGIN_TITLE', 'description' => 'Token for login title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_login_noir',
        'name' => 'Gateway Component Auth Login - Noir',
        'description' => 'Editorial auth login fragment with inline validation UX.',
        'file' => __DIR__ . '/components/auth-login-variant-noir.html',
        'tags' => ['gateway', 'component', 'auth', 'login', 'noir', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FORGOT_HREF', 'description' => 'Token for forgot href.', 'default' => '#'],
            ['token' => 'LOGIN_ACTION', 'description' => 'Token for login action.', 'default' => '#'],
            ['token' => 'LOGIN_CTA_LABEL', 'description' => 'Token for login cta label.', 'default' => 'login cta label'],
            ['token' => 'LOGIN_METHOD', 'description' => 'Token for login method.', 'default' => 'POST'],
            ['token' => 'LOGIN_SUBTITLE', 'description' => 'Token for login subtitle.', 'default' => ''],
            ['token' => 'LOGIN_TITLE', 'description' => 'Token for login title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_login_aurora',
        'name' => 'Gateway Component Auth Login - Aurora',
        'description' => 'Ambient auth login fragment with accessible status messaging.',
        'file' => __DIR__ . '/components/auth-login-variant-aurora.html',
        'tags' => ['gateway', 'component', 'auth', 'login', 'aurora', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FORGOT_HREF', 'description' => 'Token for forgot href.', 'default' => '#'],
            ['token' => 'LOGIN_ACTION', 'description' => 'Token for login action.', 'default' => '#'],
            ['token' => 'LOGIN_CTA_LABEL', 'description' => 'Token for login cta label.', 'default' => 'login cta label'],
            ['token' => 'LOGIN_METHOD', 'description' => 'Token for login method.', 'default' => 'POST'],
            ['token' => 'LOGIN_SUBTITLE', 'description' => 'Token for login subtitle.', 'default' => ''],
            ['token' => 'LOGIN_TITLE', 'description' => 'Token for login title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_register_foundry',
        'name' => 'Gateway Component Auth Register - Foundry',
        'description' => 'Registration fragment with password match guard.',
        'file' => __DIR__ . '/components/auth-register-variant-foundry.html',
        'tags' => ['gateway', 'component', 'auth', 'register', 'foundry', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'REGISTER_ACTION', 'description' => 'Token for register action.', 'default' => '#'],
            ['token' => 'REGISTER_CTA_LABEL', 'description' => 'Token for register cta label.', 'default' => 'register cta label'],
            ['token' => 'REGISTER_METHOD', 'description' => 'Token for register method.', 'default' => 'POST'],
            ['token' => 'REGISTER_TITLE', 'description' => 'Token for register title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_register_helix',
        'name' => 'Gateway Component Auth Register - Helix',
        'description' => 'Registration fragment variant with inline status feedback.',
        'file' => __DIR__ . '/components/auth-register-variant-helix.html',
        'tags' => ['gateway', 'component', 'auth', 'register', 'helix', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'REGISTER_ACTION', 'description' => 'Token for register action.', 'default' => '#'],
            ['token' => 'REGISTER_CTA_LABEL', 'description' => 'Token for register cta label.', 'default' => 'register cta label'],
            ['token' => 'REGISTER_METHOD', 'description' => 'Token for register method.', 'default' => 'POST'],
            ['token' => 'REGISTER_TITLE', 'description' => 'Token for register title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_recovery_ember',
        'name' => 'Gateway Component Auth Recovery - Ember',
        'description' => 'Password recovery fragment with email format checks.',
        'file' => __DIR__ . '/components/auth-recovery-variant-ember.html',
        'tags' => ['gateway', 'component', 'auth', 'recovery', 'ember', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'RECOVERY_ACTION', 'description' => 'Token for recovery action.', 'default' => '#'],
            ['token' => 'RECOVERY_CTA_LABEL', 'description' => 'Token for recovery cta label.', 'default' => 'recovery cta label'],
            ['token' => 'RECOVERY_METHOD', 'description' => 'Token for recovery method.', 'default' => 'POST'],
            ['token' => 'RECOVERY_TITLE', 'description' => 'Token for recovery title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_auth_recovery_orbit',
        'name' => 'Gateway Component Auth Recovery - Orbit',
        'description' => 'Password recovery fragment variant with live status.',
        'file' => __DIR__ . '/components/auth-recovery-variant-orbit.html',
        'tags' => ['gateway', 'component', 'auth', 'recovery', 'orbit', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'RECOVERY_ACTION', 'description' => 'Token for recovery action.', 'default' => '#'],
            ['token' => 'RECOVERY_CTA_LABEL', 'description' => 'Token for recovery cta label.', 'default' => 'recovery cta label'],
            ['token' => 'RECOVERY_METHOD', 'description' => 'Token for recovery method.', 'default' => 'POST'],
            ['token' => 'RECOVERY_TITLE', 'description' => 'Token for recovery title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_commerce_product_grid_rally',
        'name' => 'Gateway Component Commerce Product Grid - Rally',
        'description' => 'Commerce product grid fragment with optional empty state.',
        'file' => __DIR__ . '/components/commerce-product-grid-variant-rally.html',
        'tags' => ['gateway', 'component', 'commerce', 'product-grid', 'rally', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'PRODUCT_CARD_ITEMS_HTML', 'description' => 'Token for product card items html.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_EMPTY_STATE_HTML', 'description' => 'Token for product grid empty state html.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_EYEBROW', 'description' => 'Token for product grid eyebrow.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_LEAD', 'description' => 'Token for product grid lead.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_META', 'description' => 'Token for product grid meta.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_TITLE', 'description' => 'Token for product grid title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_commerce_product_grid_atelier',
        'name' => 'Gateway Component Commerce Product Grid - Atelier',
        'description' => 'Commerce product grid editorial variant.',
        'file' => __DIR__ . '/components/commerce-product-grid-variant-atelier.html',
        'tags' => ['gateway', 'component', 'commerce', 'product-grid', 'atelier', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'PRODUCT_CARD_ITEMS_HTML', 'description' => 'Token for product card items html.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_EMPTY_STATE_HTML', 'description' => 'Token for product grid empty state html.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_EYEBROW', 'description' => 'Token for product grid eyebrow.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_LEAD', 'description' => 'Token for product grid lead.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_META', 'description' => 'Token for product grid meta.', 'default' => ''],
            ['token' => 'PRODUCT_GRID_TITLE', 'description' => 'Token for product grid title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_commerce_cart_drawer_pivot',
        'name' => 'Gateway Component Commerce Cart Drawer - Pivot',
        'description' => 'Cart drawer fragment with ESC/backdrop close behavior.',
        'file' => __DIR__ . '/components/commerce-cart-drawer-variant-pivot.html',
        'tags' => ['gateway', 'component', 'commerce', 'cart', 'pivot', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'CART_DRAWER_CLOSE_LABEL', 'description' => 'Token for cart drawer close label.', 'default' => 'cart drawer close label'],
            ['token' => 'CART_DRAWER_EYEBROW', 'description' => 'Token for cart drawer eyebrow.', 'default' => ''],
            ['token' => 'CART_DRAWER_FOOTER_HTML', 'description' => 'Token for cart drawer footer html.', 'default' => ''],
            ['token' => 'CART_DRAWER_ITEMS_HTML', 'description' => 'Token for cart drawer items html.', 'default' => ''],
            ['token' => 'CART_DRAWER_TITLE', 'description' => 'Token for cart drawer title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_commerce_checkout_summary_rail',
        'name' => 'Gateway Component Commerce Checkout Summary - Rail',
        'description' => 'Checkout summary fragment with coupon validation.',
        'file' => __DIR__ . '/components/commerce-checkout-summary-variant-rail.html',
        'tags' => ['gateway', 'component', 'commerce', 'checkout', 'rail', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'CHECKOUT_SUMMARY_EYEBROW', 'description' => 'Token for checkout summary eyebrow.', 'default' => ''],
            ['token' => 'CHECKOUT_SUMMARY_LEAD', 'description' => 'Token for checkout summary lead.', 'default' => ''],
            ['token' => 'CHECKOUT_SUMMARY_TITLE', 'description' => 'Token for checkout summary title.', 'default' => 'Section'],
            ['token' => 'CHECKOUT_TOTALS_HTML', 'description' => 'Token for checkout totals html.', 'default' => ''],
            ['token' => 'CHECKOUT_TOTAL_ROWS_HTML', 'description' => 'Token for checkout total rows html.', 'default' => ''],
            ['token' => 'COUPON_EMPTY_ERROR', 'description' => 'Token for coupon empty error.', 'default' => 'Invalid value.'],
            ['token' => 'COUPON_FIELD_HELP', 'description' => 'Token for coupon field help.', 'default' => ''],
            ['token' => 'COUPON_FIELD_LABEL', 'description' => 'Token for coupon field label.', 'default' => 'coupon field label'],
            ['token' => 'COUPON_FIELD_PLACEHOLDER', 'description' => 'Token for coupon field placeholder.', 'default' => 'Type here...'],
            ['token' => 'COUPON_FORMAT_ERROR', 'description' => 'Token for coupon format error.', 'default' => 'Invalid value.'],
            ['token' => 'COUPON_READY_MESSAGE', 'description' => 'Token for coupon ready message.', 'default' => 'Ready.'],
            ['token' => 'COUPON_SUBMIT_LABEL', 'description' => 'Token for coupon submit label.', 'default' => 'coupon submit label'],
        ],
    ],
    [
        'id' => 'gateway_component_content_hero_orbit',
        'name' => 'Gateway Component Content Hero - Orbit',
        'description' => 'Hero content fragment with callouts and CTA slots.',
        'file' => __DIR__ . '/components/content-hero-variant-orbit.html',
        'tags' => ['gateway', 'component', 'content', 'hero', 'orbit', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'CALLOUT_LABEL_1', 'description' => 'Token for callout label 1.', 'default' => ''],
            ['token' => 'CALLOUT_LABEL_2', 'description' => 'Token for callout label 2.', 'default' => ''],
            ['token' => 'CALLOUT_NOTE_1', 'description' => 'Token for callout note 1.', 'default' => ''],
            ['token' => 'CALLOUT_NOTE_2', 'description' => 'Token for callout note 2.', 'default' => ''],
            ['token' => 'CALLOUT_VALUE_1', 'description' => 'Token for callout value 1.', 'default' => '42'],
            ['token' => 'CALLOUT_VALUE_2', 'description' => 'Token for callout value 2.', 'default' => '7'],
            ['token' => 'EYEBROW', 'description' => 'Token for eyebrow.', 'default' => ''],
            ['token' => 'HEADING', 'description' => 'Token for heading.', 'default' => 'Section heading'],
            ['token' => 'HERO_POINTS_HTML', 'description' => 'Token for hero points html.', 'default' => ''],
            ['token' => 'PRIMARY_CTA_HREF', 'description' => 'Token for primary cta href.', 'default' => '#'],
            ['token' => 'PRIMARY_CTA_LABEL', 'description' => 'Token for primary cta label.', 'default' => 'primary cta label'],
            ['token' => 'SECONDARY_CTA_HREF', 'description' => 'Token for secondary cta href.', 'default' => '#'],
            ['token' => 'SECONDARY_CTA_LABEL', 'description' => 'Token for secondary cta label.', 'default' => 'secondary cta label'],
            ['token' => 'SECTION_LABEL', 'description' => 'Token for section label.', 'default' => 'section label'],
            ['token' => 'SIDEBAR_ITEMS_HTML', 'description' => 'Token for sidebar items html.', 'default' => ''],
            ['token' => 'SIDEBAR_LABEL', 'description' => 'Token for sidebar label.', 'default' => 'sidebar label'],
            ['token' => 'SUBHEADING', 'description' => 'Token for subheading.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_content_feature_grid_vault',
        'name' => 'Gateway Component Content Feature Grid - Vault',
        'description' => 'Feature grid fragment for modular landing pages.',
        'file' => __DIR__ . '/components/content-feature-grid-variant-vault.html',
        'tags' => ['gateway', 'component', 'content', 'features', 'vault', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FEATURE_CARDS_HTML', 'description' => 'Token for feature cards html.', 'default' => ''],
            ['token' => 'HEADING', 'description' => 'Token for heading.', 'default' => 'Section heading'],
            ['token' => 'PRIMARY_CTA_HREF', 'description' => 'Token for primary cta href.', 'default' => '#'],
            ['token' => 'PRIMARY_CTA_LABEL', 'description' => 'Token for primary cta label.', 'default' => 'primary cta label'],
            ['token' => 'SECONDARY_CTA_HREF', 'description' => 'Token for secondary cta href.', 'default' => '#'],
            ['token' => 'SECONDARY_CTA_LABEL', 'description' => 'Token for secondary cta label.', 'default' => 'secondary cta label'],
            ['token' => 'SECTION_LABEL', 'description' => 'Token for section label.', 'default' => 'section label'],
            ['token' => 'SUBHEADING', 'description' => 'Token for subheading.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_content_faq_prism',
        'name' => 'Gateway Component Content FAQ - Prism',
        'description' => 'FAQ accordion fragment with keyboard-friendly toggles.',
        'file' => __DIR__ . '/components/content-faq-accordion-variant-prism.html',
        'tags' => ['gateway', 'component', 'content', 'faq', 'prism', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FAQ_ITEMS_HTML', 'description' => 'Token for faq items html.', 'default' => ''],
            ['token' => 'FAQ_ROOT_ID', 'description' => 'Token for faq root id.', 'default' => 'block-root'],
            ['token' => 'HEADING', 'description' => 'Token for heading.', 'default' => 'Section heading'],
            ['token' => 'HELP_LABEL', 'description' => 'Token for help label.', 'default' => 'help label'],
            ['token' => 'HELP_TEXT', 'description' => 'Token for help text.', 'default' => ''],
            ['token' => 'SECTION_LABEL', 'description' => 'Token for section label.', 'default' => 'section label'],
            ['token' => 'SUBHEADING', 'description' => 'Token for subheading.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_content_cta_band_summit',
        'name' => 'Gateway Component Content CTA Band - Summit',
        'description' => 'CTA band fragment for campaign and conversion sections.',
        'file' => __DIR__ . '/components/content-cta-band-variant-summit.html',
        'tags' => ['gateway', 'component', 'content', 'cta', 'summit', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'CTA_POINTS_HTML', 'description' => 'Token for cta points html.', 'default' => ''],
            ['token' => 'HEADING', 'description' => 'Token for heading.', 'default' => 'Section heading'],
            ['token' => 'PRIMARY_CTA_HREF', 'description' => 'Token for primary cta href.', 'default' => '#'],
            ['token' => 'PRIMARY_CTA_LABEL', 'description' => 'Token for primary cta label.', 'default' => 'primary cta label'],
            ['token' => 'SECONDARY_CTA_HREF', 'description' => 'Token for secondary cta href.', 'default' => '#'],
            ['token' => 'SECONDARY_CTA_LABEL', 'description' => 'Token for secondary cta label.', 'default' => 'secondary cta label'],
            ['token' => 'SECTION_LABEL', 'description' => 'Token for section label.', 'default' => 'section label'],
            ['token' => 'SIDEBAR_LABEL', 'description' => 'Token for sidebar label.', 'default' => 'sidebar label'],
            ['token' => 'SUBHEADING', 'description' => 'Token for subheading.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_account_dashboard_axis',
        'name' => 'Gateway Component Account Dashboard - Axis',
        'description' => 'Account dashboard fragment with tabbed panels.',
        'file' => __DIR__ . '/components/account-dashboard-variant-axis.html',
        'tags' => ['gateway', 'component', 'account', 'dashboard', 'axis', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'ACCOUNT_EYEBROW_LABEL', 'description' => 'Token for account eyebrow label.', 'default' => 'account eyebrow label'],
            ['token' => 'ACCOUNT_META_HTML', 'description' => 'Token for account meta html.', 'default' => ''],
            ['token' => 'ACCOUNT_META_LABEL', 'description' => 'Token for account meta label.', 'default' => 'account meta label'],
            ['token' => 'ACCOUNT_NOTIFICATIONS_ACTION_HREF', 'description' => 'Token for account notifications action href.', 'default' => '#'],
            ['token' => 'ACCOUNT_NOTIFICATIONS_ACTION_LABEL', 'description' => 'Token for account notifications action label.', 'default' => 'account notifications action label'],
            ['token' => 'ACCOUNT_NOTIFICATIONS_HTML', 'description' => 'Token for account notifications html.', 'default' => ''],
            ['token' => 'ACCOUNT_NOTIFICATIONS_PANEL_TITLE', 'description' => 'Token for account notifications panel title.', 'default' => 'Section'],
            ['token' => 'ACCOUNT_NOTIFICATIONS_TAB_LABEL', 'description' => 'Token for account notifications tab label.', 'default' => 'account notifications tab label'],
            ['token' => 'ACCOUNT_ORDERS_ACTION_HREF', 'description' => 'Token for account orders action href.', 'default' => '#'],
            ['token' => 'ACCOUNT_ORDERS_ACTION_LABEL', 'description' => 'Token for account orders action label.', 'default' => 'account orders action label'],
            ['token' => 'ACCOUNT_ORDERS_HTML', 'description' => 'Token for account orders html.', 'default' => ''],
            ['token' => 'ACCOUNT_ORDERS_PANEL_TITLE', 'description' => 'Token for account orders panel title.', 'default' => 'Section'],
            ['token' => 'ACCOUNT_ORDERS_TAB_LABEL', 'description' => 'Token for account orders tab label.', 'default' => 'account orders tab label'],
            ['token' => 'ACCOUNT_OVERVIEW_ACTION_HREF', 'description' => 'Token for account overview action href.', 'default' => '#'],
            ['token' => 'ACCOUNT_OVERVIEW_ACTION_LABEL', 'description' => 'Token for account overview action label.', 'default' => 'account overview action label'],
            ['token' => 'ACCOUNT_OVERVIEW_HTML', 'description' => 'Token for account overview html.', 'default' => ''],
            ['token' => 'ACCOUNT_OVERVIEW_PANEL_TITLE', 'description' => 'Token for account overview panel title.', 'default' => 'Section'],
            ['token' => 'ACCOUNT_OVERVIEW_TAB_LABEL', 'description' => 'Token for account overview tab label.', 'default' => 'account overview tab label'],
            ['token' => 'ACCOUNT_SECURITY_ACTION_HREF', 'description' => 'Token for account security action href.', 'default' => '#'],
            ['token' => 'ACCOUNT_SECURITY_ACTION_LABEL', 'description' => 'Token for account security action label.', 'default' => 'account security action label'],
            ['token' => 'ACCOUNT_SECURITY_HTML', 'description' => 'Token for account security html.', 'default' => ''],
            ['token' => 'ACCOUNT_SECURITY_PANEL_TITLE', 'description' => 'Token for account security panel title.', 'default' => 'Section'],
            ['token' => 'ACCOUNT_SECURITY_TAB_LABEL', 'description' => 'Token for account security tab label.', 'default' => 'account security tab label'],
            ['token' => 'ACCOUNT_SUBTITLE', 'description' => 'Token for account subtitle.', 'default' => ''],
            ['token' => 'ACCOUNT_TABLIST_LABEL', 'description' => 'Token for account tablist label.', 'default' => 'account tablist label'],
            ['token' => 'ACCOUNT_TITLE', 'description' => 'Token for account title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_account_orders_ledger',
        'name' => 'Gateway Component Account Orders Ledger',
        'description' => 'Account orders fragment with responsive table scaffolding.',
        'file' => __DIR__ . '/components/account-orders-table-variant-ledger.html',
        'tags' => ['gateway', 'component', 'account', 'orders', 'ledger', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'ORDERS_COLUMN_ACTIONS_LABEL', 'description' => 'Token for orders column actions label.', 'default' => 'orders column actions label'],
            ['token' => 'ORDERS_COLUMN_DATE_LABEL', 'description' => 'Token for orders column date label.', 'default' => 'orders column date label'],
            ['token' => 'ORDERS_COLUMN_FULFILLMENT_LABEL', 'description' => 'Token for orders column fulfillment label.', 'default' => 'orders column fulfillment label'],
            ['token' => 'ORDERS_COLUMN_ID_LABEL', 'description' => 'Token for orders column id label.', 'default' => 'orders column id label'],
            ['token' => 'ORDERS_COLUMN_STATUS_LABEL', 'description' => 'Token for orders column status label.', 'default' => 'orders column status label'],
            ['token' => 'ORDERS_COLUMN_TOTAL_LABEL', 'description' => 'Token for orders column total label.', 'default' => 'orders column total label'],
            ['token' => 'ORDERS_EMPTY_HTML', 'description' => 'Token for orders empty html.', 'default' => ''],
            ['token' => 'ORDERS_EYEBROW_LABEL', 'description' => 'Token for orders eyebrow label.', 'default' => 'orders eyebrow label'],
            ['token' => 'ORDERS_FILTERS_HTML', 'description' => 'Token for orders filters html.', 'default' => ''],
            ['token' => 'ORDERS_FILTERS_LABEL', 'description' => 'Token for orders filters label.', 'default' => 'orders filters label'],
            ['token' => 'ORDERS_ROWS_HTML', 'description' => 'Token for orders rows html.', 'default' => ''],
            ['token' => 'ORDERS_SUBTITLE', 'description' => 'Token for orders subtitle.', 'default' => ''],
            ['token' => 'ORDERS_SUMMARY_HTML', 'description' => 'Token for orders summary html.', 'default' => ''],
            ['token' => 'ORDERS_SUMMARY_LABEL', 'description' => 'Token for orders summary label.', 'default' => 'orders summary label'],
            ['token' => 'ORDERS_TABLE_CAPTION', 'description' => 'Token for orders table caption.', 'default' => ''],
            ['token' => 'ORDERS_TITLE', 'description' => 'Token for orders title.', 'default' => 'Section'],
            ['token' => 'ORDERS_TOOLBAR_HTML', 'description' => 'Token for orders toolbar html.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_account_security_sentinel',
        'name' => 'Gateway Component Account Security - Sentinel',
        'description' => 'Account security panel fragment with collapsible states.',
        'file' => __DIR__ . '/components/account-security-panel-variant-sentinel.html',
        'tags' => ['gateway', 'component', 'account', 'security', 'sentinel', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SECURITY_COLLAPSE_ALL_LABEL', 'description' => 'Token for security collapse all label.', 'default' => 'security collapse all label'],
            ['token' => 'SECURITY_DEVICES_HTML', 'description' => 'Token for security devices html.', 'default' => ''],
            ['token' => 'SECURITY_DEVICES_META', 'description' => 'Token for security devices meta.', 'default' => ''],
            ['token' => 'SECURITY_DEVICES_STATE_LABEL', 'description' => 'Token for security devices state label.', 'default' => 'security devices state label'],
            ['token' => 'SECURITY_DEVICES_TITLE', 'description' => 'Token for security devices title.', 'default' => 'Section'],
            ['token' => 'SECURITY_EYEBROW_LABEL', 'description' => 'Token for security eyebrow label.', 'default' => 'security eyebrow label'],
            ['token' => 'SECURITY_MFA_HTML', 'description' => 'Token for security mfa html.', 'default' => ''],
            ['token' => 'SECURITY_MFA_META', 'description' => 'Token for security mfa meta.', 'default' => ''],
            ['token' => 'SECURITY_MFA_STATE_LABEL', 'description' => 'Token for security mfa state label.', 'default' => 'security mfa state label'],
            ['token' => 'SECURITY_MFA_TITLE', 'description' => 'Token for security mfa title.', 'default' => 'Section'],
            ['token' => 'SECURITY_PASSWORD_HTML', 'description' => 'Token for security password html.', 'default' => ''],
            ['token' => 'SECURITY_PASSWORD_META', 'description' => 'Token for security password meta.', 'default' => ''],
            ['token' => 'SECURITY_PASSWORD_STATE_LABEL', 'description' => 'Token for security password state label.', 'default' => 'security password state label'],
            ['token' => 'SECURITY_PASSWORD_TITLE', 'description' => 'Token for security password title.', 'default' => 'Section'],
            ['token' => 'SECURITY_RECOVERY_HTML', 'description' => 'Token for security recovery html.', 'default' => ''],
            ['token' => 'SECURITY_RECOVERY_META', 'description' => 'Token for security recovery meta.', 'default' => ''],
            ['token' => 'SECURITY_RECOVERY_STATE_LABEL', 'description' => 'Token for security recovery state label.', 'default' => 'security recovery state label'],
            ['token' => 'SECURITY_RECOVERY_TITLE', 'description' => 'Token for security recovery title.', 'default' => 'Section'],
            ['token' => 'SECURITY_SUBTITLE', 'description' => 'Token for security subtitle.', 'default' => ''],
            ['token' => 'SECURITY_TITLE', 'description' => 'Token for security title.', 'default' => 'Section'],
        ],
    ],
    [
        'id' => 'gateway_component_account_notifications_pulsegrid',
        'name' => 'Gateway Component Account Notifications - Pulsegrid',
        'description' => 'Notification center fragment with read-state UI behavior.',
        'file' => __DIR__ . '/components/account-notification-center-variant-pulsegrid.html',
        'tags' => ['gateway', 'component', 'account', 'notifications', 'pulsegrid', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'NOTIFICATIONS_EMPTY_HTML', 'description' => 'Token for notifications empty html.', 'default' => ''],
            ['token' => 'NOTIFICATIONS_EYEBROW_LABEL', 'description' => 'Token for notifications eyebrow label.', 'default' => 'notifications eyebrow label'],
            ['token' => 'NOTIFICATIONS_FILTERS_HTML', 'description' => 'Token for notifications filters html.', 'default' => ''],
            ['token' => 'NOTIFICATIONS_FILTERS_LABEL', 'description' => 'Token for notifications filters label.', 'default' => 'notifications filters label'],
            ['token' => 'NOTIFICATIONS_LIST_LABEL', 'description' => 'Token for notifications list label.', 'default' => 'notifications list label'],
            ['token' => 'NOTIFICATIONS_SUBTITLE', 'description' => 'Token for notifications subtitle.', 'default' => ''],
            ['token' => 'NOTIFICATIONS_TITLE', 'description' => 'Token for notifications title.', 'default' => 'Section'],
            ['token' => 'NOTIFICATION_ITEMS_HTML', 'description' => 'Token for notification items html.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_search_variant_signal',
        'name' => 'Gateway Search Variant - Signal',
        'description' => 'Tailwind glass-like search UX with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-signal.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Discover verified pages across the mesh.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_FETCH_MODE', 'description' => 'Index fetch mode for template-call or public-read routing.', 'default' => 'template_call'],
            ['token' => 'PUBLIC_INDEX_ENDPOINT', 'description' => 'Public-read endpoint used when index fetches move off template-call.', 'default' => '/api/public/site-index'],
            ['token' => 'INDEX_REQUEST_BODY_JSON', 'description' => 'JSON body sent to the public-read index endpoint.', 'default' => '{}'],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Find route, domain, or page id...'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
    [
        'id' => 'gateway_search_variant_bastion',
        'name' => 'Gateway Search Variant - Bastion',
        'description' => 'Tailwind high-contrast console style with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-bastion.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Route requests safely through the gateway boundary.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_FETCH_MODE', 'description' => 'Index fetch mode for template-call or public-read routing.', 'default' => 'template_call'],
            ['token' => 'PUBLIC_INDEX_ENDPOINT', 'description' => 'Public-read endpoint used when index fetches move off template-call.', 'default' => '/api/public/site-index'],
            ['token' => 'INDEX_REQUEST_BODY_JSON', 'description' => 'JSON body sent to the public-read index endpoint.', 'default' => '{}'],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'route:/, page:home, domain:shop.example'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
    [
        'id' => 'gateway_search_variant_horizon',
        'name' => 'Gateway Search Variant - Horizon',
        'description' => 'Tailwind editorial layout with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-horizon.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Search by route, domain, or page id.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_FETCH_MODE', 'description' => 'Index fetch mode for template-call or public-read routing.', 'default' => 'template_call'],
            ['token' => 'PUBLIC_INDEX_ENDPOINT', 'description' => 'Public-read endpoint used when index fetches move off template-call.', 'default' => '/api/public/site-index'],
            ['token' => 'INDEX_REQUEST_BODY_JSON', 'description' => 'JSON body sent to the public-read index endpoint.', 'default' => '{}'],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Try route:/about or page:contact'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
];
