<?php

declare(strict_types=1);

return [
    [
        'id' => 'module_readme',
        'name' => 'Module README',
        'description' => 'Standard README describing config, CLI, telemetry, and integration hooks.',
        'file' => __DIR__ . '/module-readme.md',
        'tags' => ['docs', 'bootstrap'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-write', 'blackcat-darkmesh-ao'],
        'placeholders' => [
            ['token' => 'MODULE_NAME', 'description' => 'Display name for the repository.', 'required' => true],
            ['token' => 'DESCRIPTION', 'description' => 'One-line description/mission.', 'required' => true],
            ['token' => 'CLI_USAGE', 'description' => 'CLI example to surface in README.', 'default' => 'php bin/<repo>'],
            ['token' => 'TELEMETRY_DESC', 'description' => 'How telemetry is exposed (Prometheus endpoints, etc).', 'default' => 'Exports Prometheus metrics.'],
        ],
    ],
    [
        'id' => 'module_roadmap',
        'name' => 'Module Roadmap',
        'description' => 'Stage-by-stage roadmap stub referencing integration partners.',
        'file' => __DIR__ . '/module-roadmap.md',
        'tags' => ['docs', 'roadmap'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-write', 'blackcat-darkmesh-ao'],
        'placeholders' => [
            ['token' => 'MODULE_NAME', 'description' => 'Repository display name.', 'required' => true],
            ['token' => 'VISION', 'description' => 'North-star goal for the module.', 'required' => true],
            ['token' => 'STAGE1_FOCUS', 'description' => 'Stage 1 focus description.', 'required' => true],
            ['token' => 'STAGE2_FOCUS', 'description' => 'Stage 2 focus description.', 'required' => true],
            ['token' => 'COMPLIANCE_OWNER', 'description' => 'Person/alias accountable for compliance sign-off.', 'default' => 'governance@blackcat'],
        ],
    ],
    [
        'id' => 'gateway_search_shell_core',
        'name' => 'Gateway Search Shell - Core',
        'description' => 'Composable shell for gateway search pages; inject rendered menu/search/results/footer fragments.',
        'file' => __DIR__ . '/gateway-search-shell-core.html',
        'tags' => ['gateway', 'search', 'ux', 'shell', 'component-kit', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Document title used by browser tabs.', 'required' => true],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array used when index API is unavailable.', 'default' => '[]'],
            ['token' => 'MENU_COMPONENT', 'description' => 'Rendered menu fragment HTML.', 'required' => true],
            ['token' => 'SEARCH_COMPONENT', 'description' => 'Rendered search/hero fragment HTML.', 'required' => true],
            ['token' => 'RESULTS_COMPONENT', 'description' => 'Rendered index/results fragment HTML.', 'required' => true],
            ['token' => 'FOOTER_COMPONENT', 'description' => 'Rendered footer fragment HTML.', 'required' => true],
            ['token' => 'SHELL_BODY_CLASS', 'description' => 'Optional extra class string for shell wrapper.', 'default' => ''],
            ['token' => 'SHELL_EXTRA_CSS', 'description' => 'Optional extra CSS appended after shell defaults.', 'default' => ''],
        ],
    ],
    [
        'id' => 'gateway_component_menu_pulse',
        'name' => 'Gateway Component Menu - Pulse',
        'description' => 'Neon/glass menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-pulse.html',
        'tags' => ['gateway', 'component', 'menu', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#catalog\">Catalog</a><a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#explore\">Explore</a><a class=\"rounded-lg border border-white/20 px-3 py-2 hover:bg-white/10\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_menu_forge',
        'name' => 'Gateway Component Menu - Forge',
        'description' => 'Brutalist menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-forge.html',
        'tags' => ['gateway', 'component', 'menu', 'forge', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#catalog\">Catalog</a><a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#explore\">Explore</a><a class=\"border-2 border-black bg-black px-3 py-2 text-amber-200\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_menu_zenith',
        'name' => 'Gateway Component Menu - Zenith',
        'description' => 'Editorial menu fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-menu-variant-zenith.html',
        'tags' => ['gateway', 'component', 'menu', 'zenith', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Brand title shown in top navigation.', 'required' => true],
            ['token' => 'BRAND_HREF', 'description' => 'Target URL for clicking the brand title.', 'default' => '/'],
            ['token' => 'MENU_ITEMS_HTML', 'description' => 'Navigation links HTML fragment.', 'default' => '<a class=\"hover:text-slate-900/70\" href=\"#catalog\">Catalog</a><a class=\"hover:text-slate-900/70\" href=\"#explore\">Explore</a><a class=\"hover:text-slate-900/70\" href=\"#about\">About</a>'],
            ['token' => 'MENU_CTA_LABEL', 'description' => 'Label for the right-side call-to-action.', 'default' => 'Open Map'],
            ['token' => 'MENU_CTA_HREF', 'description' => 'URL for the right-side call-to-action.', 'default' => '#'],
        ],
    ],
    [
        'id' => 'gateway_component_search_pulse',
        'name' => 'Gateway Component Search - Pulse',
        'description' => 'Neon hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-pulse.html',
        'tags' => ['gateway', 'component', 'search', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Discover verified pages across the mesh.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Find route, domain, or page id...'],
        ],
    ],
    [
        'id' => 'gateway_component_search_atlas',
        'name' => 'Gateway Component Search - Atlas',
        'description' => 'Brutalist hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-atlas.html',
        'tags' => ['gateway', 'component', 'search', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Route through the public mesh with deterministic records.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'domain:example.com or route:/about'],
        ],
    ],
    [
        'id' => 'gateway_component_search_lumen',
        'name' => 'Gateway Component Search - Lumen',
        'description' => 'Editorial hero/search fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-search-variant-lumen.html',
        'tags' => ['gateway', 'component', 'search', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Main heading shown above search form.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Sub-heading under main title.', 'default' => 'Search by route, domain, or page id.'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Try route:/about or page:contact'],
        ],
    ],
    [
        'id' => 'gateway_component_results_pulse',
        'name' => 'Gateway Component Results - Pulse',
        'description' => 'Neon result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-pulse.html',
        'tags' => ['gateway', 'component', 'results', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_results_atlas',
        'name' => 'Gateway Component Results - Atlas',
        'description' => 'Brutalist result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-atlas.html',
        'tags' => ['gateway', 'component', 'results', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_results_lumen',
        'name' => 'Gateway Component Results - Lumen',
        'description' => 'Editorial result-grid fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-results-variant-lumen.html',
        'tags' => ['gateway', 'component', 'results', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label describing fairness/randomized ordering mode.', 'default' => 'EU fairness mode: randomized order per refresh'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_pulse',
        'name' => 'Gateway Component Footer - Pulse',
        'description' => 'Neon footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-pulse.html',
        'tags' => ['gateway', 'component', 'footer', 'pulse', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"hover:text-cyan-200\" href=\"#\">Status</a><a class=\"hover:text-cyan-200\" href=\"#\">Policy</a><a class=\"hover:text-cyan-200\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_atlas',
        'name' => 'Gateway Component Footer - Atlas',
        'description' => 'Brutalist footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-atlas.html',
        'tags' => ['gateway', 'component', 'footer', 'atlas', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"underline\" href=\"#\">Status</a><a class=\"underline\" href=\"#\">Policy</a><a class=\"underline\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_component_footer_lumen',
        'name' => 'Gateway Component Footer - Lumen',
        'description' => 'Editorial footer fragment for composable gateway pages.',
        'file' => __DIR__ . '/components/gateway-footer-variant-lumen.html',
        'tags' => ['gateway', 'component', 'footer', 'lumen', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'FOOTER_NOTE', 'description' => 'Main footer note text.', 'default' => 'Public templates are deterministic and auditable.'],
            ['token' => 'FOOTER_LINKS_HTML', 'description' => 'Footer links HTML fragment.', 'default' => '<a class=\"hover:text-slate-900\" href=\"#\">Status</a><a class=\"hover:text-slate-900\" href=\"#\">Policy</a><a class=\"hover:text-slate-900\" href=\"#\">Source</a>'],
        ],
    ],
    [
        'id' => 'gateway_search_variant_signal',
        'name' => 'Gateway Search Variant - Signal',
        'description' => 'Tailwind glass-like search UX with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-signal.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Discover verified pages across the mesh.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Find route, domain, or page id...'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
    [
        'id' => 'gateway_search_variant_bastion',
        'name' => 'Gateway Search Variant - Bastion',
        'description' => 'Tailwind high-contrast console style with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-bastion.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Route requests safely through the gateway boundary.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'route:/, page:home, domain:shop.example'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
    [
        'id' => 'gateway_search_variant_horizon',
        'name' => 'Gateway Search Variant - Horizon',
        'description' => 'Tailwind editorial layout with fair randomized index ordering.',
        'file' => __DIR__ . '/gateway-search-variant-horizon.html',
        'tags' => ['gateway', 'search', 'ux', 'public-template'],
        'integrations' => ['blackcat-darkmesh-gateway', 'blackcat-darkmesh-ao', 'blackcat-darkmesh-write'],
        'placeholders' => [
            ['token' => 'SITE_TITLE', 'description' => 'Public title shown to end users.', 'required' => true],
            ['token' => 'SITE_TAGLINE', 'description' => 'Short subtitle under the title.', 'default' => 'Search by route, domain, or page id.'],
            ['token' => 'GATEWAY_ORIGIN', 'description' => 'Gateway origin used for API calls.', 'required' => true],
            ['token' => 'SEARCH_ACTION', 'description' => 'Template action used for route resolution.', 'default' => 'public.resolve-route'],
            ['token' => 'INDEX_ACTION', 'description' => 'Optional backend action for live public site-index fetch.', 'default' => ''],
            ['token' => 'INDEX_LIMIT', 'description' => 'Max index entries requested from gateway.', 'default' => '120'],
            ['token' => 'INDEX_MODE_LABEL', 'description' => 'Label explaining random index ordering policy.', 'default' => 'EU fairness mode: randomized order per refresh'],
            ['token' => 'SEARCH_PLACEHOLDER', 'description' => 'Search input placeholder text.', 'default' => 'Try route:/about or page:contact'],
            ['token' => 'INDEX_SEED_JSON', 'description' => 'Fallback JSON array of site/page entries used if index API is unavailable.', 'default' => '[]'],
        ],
    ],
];
